version: '3.0'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - inet_net

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: php-custom
    restart: always
    expose:
      - "80"
    networks: 
      - proxy_net
      - inet_net
    links:
      - mysql

  pma:
    image: phpmyadmin:5.1
    restart: always
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - proxy_net
      - inet_net
    links:
      - mysql

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-custom
    networks:
      - proxy_net
      - ext_net
    ports:
      - "80:80" # expose port 80 host ke 80 container
    links:
      - web
      - pma
    healthcheck:
      test:  curl -f http://localhost/ || exit 0
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  ext_net:
  proxy_net:
  inet_net:
  